#!/bin/sh
mkdir -p cert
rm -f cert/server.key cert/server.crt
openssl req -x509 -newkey rsa:4096 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout cert/server.key -out cert/server.crt -days 365 -nodes
